import 'package:flutter/material.dart';

const Color white = Color(0xffffffff);
const Color blue = Color(0xff4076e3);
const Color bl = Color(0xff7db2ff);
const Color ongo = Color(0xffff6856);
const Color blac = Color(0xff3a3939);
const Color darkblue = Color(0xff385582);
const Color bl1 = Color(0xffe1ebfc);
const Color grey = Color(0xffa6abae);
const Color bl2 = Color(0xff4a6c93);
const Color bl3 = Color(0xffb7d9ff);
const Color bl4 = Color(0xff47b7d9ff);
const Color tp = Color(0xff4076e3);
const Color bgp = Color(0xffd5e1f9);
const Color ts = Color(0xffd4a807);
const Color bgs = Color(0xfffef9ce);
const Color td = Color(0xffff6856);
const Color bgd = Color(0xffffe5e2);
const Color g = Color(0xfff6f6f7);
const Color bl5 = Color(0xff4993ff);
const Color whites = Color(0xffb8ffffff);
const Color whitet = Color(0xff70fefbfb);
const Color agray = Color(0xffb5bdd3);
const Color dark = Color(0xff70a9ff);
const Color whiteo = Color(0xffe1edff);
const Color blu = Color(0xfff2f8ff);
const Color gray = Color(0xffacacac);
const Color blu1 = Color(0xffbac6e0);
const Color blu2 = Color(0xff9108449b);
const Color bshaow = Color(0xff5089Fd);
const Color ic = Color(0xffF6FAFF);
const Color panc = Color(0xff8ca0d7);
//const #b8ffffff
String stc_font = "STC";
double radius = 8;
double radius2 = 19;
String tok;
